name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,1,2,15,29,30,31,45,58,59 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch weis1 data
      run: |-
        bash weis1.curl > weis1.html
    - name: Fetch weis2 data
      run: |-
        bash weis2.curl > weis2.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
